pipeline {
    agent { label 'JENKINS-AGENT' }

    tools {
        jdk 'java21'
        maven 'maven3'
    }

    stages {

        stage("Cleanup Workspace") {
            steps {
                cleanWs()
            }
        }

        stage("Checkout from SCM") {
            steps {
                git branch: 'main',
                    credentialsId: 'github',
                    url: 'https://github.com/Mradul-code/register-guide'
            }
        }

        stage("Build Application") {
            steps {
                dir('register-app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage("Test Application") {
            steps {
                dir('register-app') {
                    sh 'mvn test'
                }
            }
        }

        stage("SonarQube Analysis") {
            steps {
                dir('register-app') {
                    withSonarQubeEnv('sonarqube-server') {
                        sh 'mvn clean verify sonar:sonar'
                    }
                }
            }
        }

        stage("Quality Gate") {
            steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'jenkins-sonarqube-token
                }
            }
        }
    }
}
