pipeline {
    agent { label 'JENKINS-AGENT' }

    tools {
        jdk 'java21'
        maven 'maven3'
    }

    stages {

        stage("Cleanup Workspace") {
            steps {
                cleanWs()
            }
        }

        stage("Checkout from SCM") {
            steps {
                git branch: 'main',
                    credentialsId: 'github',
                    url: 'https://github.com/Mradul-code/register-guide'
            }
        }

        stage("Build Application") {
            steps {
                dir('register-app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage("Test Application") {
            steps {
                dir('register-app') {
                    sh 'mvn test'
                }
            }
        }  stage("SonarQube Analysis"){
           steps {
	           script {
		        withSonarQubeEnv(credentialsId: 'jenkins-sonarqube-token') { 
                        sh "mvn sonar:sonar"
		        }
	           }	
           }
       }

       stage("Quality Gate"){
           steps {
               script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'jenkins-sonarqube-token'
                }	
            }

        }
    }
}
